# Generated by Django 2.2.17 on 2020-12-25 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanresult',
            name='status',
            field=models.CharField(choices=[('PEN', 'Pending'), ('SCS', 'Success'), ('FLD', 'Failed')], default='PEN', max_length=3),
        ),
    ]
