# Generated by Django 2.2.17 on 2020-12-25 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_scanresult_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanresult',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='has_error',
            field=models.BooleanField(default=False),
        ),
    ]
