# Generated by Django 2.2.17 on 2020-12-25 18:16

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201225_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanresult',
            name='result',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
